InfyOmLabs/laravel-generator

- src/Common/CommandData.php
- src/Utils/TableFieldsGenerator.php
If a user does not pass the primary CLI option and supplies fromTable/tableName, set the primary option by querying database schema
> Pull primary key from DB schema if not provided via CLI option

- src/Commands/Publish/PublishTemplateCommand.php
It looks like, when fixing issue #98, the PublishTemplateCommand was relocated, but the committer missed the use of `__DIR__` in the file, and didn't update the path to account for the additional directory depth, so `php artisan infyom.publish:templates` was only creating empty directories instead of actually publishing anything.  This commit fixes that.
> Fix infyom.publish:templates

- templates/scaffold/datatable.stub
This is datatables-actions.stub for this pull-request
I thing it was not good idea to hardcode template inside DataTable class and move it to resources/views
```
{!! Form::open(['route' => ['$ROUTES_AS_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
<a href="{{ route('$ROUTES_AS_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.show', $id) }}" class='btn btn-default btn-xs'>
<i class="glyphicon glyphicon-eye-open"></i>
</a>
<a href="{{ route('$ROUTES_AS_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.edit', $id) }}" class='btn btn-default btn-xs'>
<i class="glyphicon glyphicon-edit"></i>
</a>
{!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
'type' => 'submit',
'class' => 'btn btn-danger btn-xs',
'onclick' => "return confirm('Are you sure?')"
]) !!} …
```
> [~] datatables stub updated to remove hardcoded blade template;

- src/Generators/ModelGenerator.php
- src/Generators/SwaggerGenerator.php
Model required fields must be surrounded by double quotes in swagger annotations.
> Required fields need double quotes.

- templates/scaffold/controller/datatable_controller.stub
I fixed the bug where datatable_controller used the AppBaseController class from the vendor package instead from the published class.
cheers for the great package
> fix datatable_controller AppBaseController namespace

- src/Utils/TableFieldsGenerator.php
When generating from a table you get an error: 
`[Symfony\Component\Debug\Exception\FatalThrowableError] 
Call to a member function isPrimary() on string`
> Fix for getting primary key when generating from table

- src/Common/GeneratorConfig.php
- templates/api/test/api_test.stub
- templates/test/repository_test.stub
- templates/vuejs/test/api_test.stub
I noticed that specifying a custom primary key name using `--primary` doesn't have an effect on the view scripts, they still use `->id` to access the ID. This results in the action buttons linking to the edit/delete routes without an ID, what again results in a `NotFoundHttpException`.
This adds the primary option (or `id` if not set) as a dynamic variable `$PRIMARY_KEY_NAME$`. I will add PRs to use this variable in *adminlte-templates* and *core-templates*.
> primary option used in views

- src/Utils/GeneratorFieldsInputUtil.php
Hi,
as I mentioned in [this issue](https://github.com/InfyOmLabs/laravel-generator/issues/283) labels for `select` and `radio`s are not generated. 
Please also update in 5.2
> labels are not generated for Select: fixed

- src/Common/GeneratorFieldRelation.php
At present, there is a side effect when `Common\GeneratorFieldRelation::generateRelation` is run, removing the first element of the relation inputs, such that outputs are different on the second call (for instance, when generating JSON output after model output). This copies the input array to avoid `array_shift` removing the element permanently.
> Use copy of inputs array before applying array_shift

- src/Generators/TestTraitGenerator.php
For enum fields infyom:api_scaffold command is failed with the error
`[Symfony\Component\Debug\Exception\FatalThrowableError]                    
Cannot use object of type InfyOm\Generator\Common\GeneratorField as array`
This change repair the access to field attribute
> Fix enum in TestTraitGenerator.php

- templates/test/repository_test.stub
Generated use statements was incorrect when using "--prefix" option. Hardcoded "App\Models" and "App\Repositories" namespaces are replaced with proper variables.
> Fixed incorrect use statements in repository_test.stub

- src/Common/BaseRepository.php
Fixes #464 - The method getForeignKey() was renamed to getQualifiedForeignKeyName() in Laravel 5.4
> Fixes #464

- src/Utils/TableFieldsGenerator.php
Here's a quick fix for #476 which will cover most cases, although a BIT is a *bit* more than a boolean: https://dev.mysql.com/doc/refman/5.7/en/bit-type.html
An alternative would be to allow the end user to declare/override its own mapping from the configuration file.
> Fix #476: Map BIT type to BOOLEAN

- config/laravel_generator.php
- src/Commands/Publish/LayoutPublishCommand.php
- src/Commands/Publish/PublishTemplateCommand.php
- src/Generators/Scaffold/ControllerGenerator.php
- src/Generators/Scaffold/MenuGenerator.php
- src/Generators/Scaffold/ViewGenerator.php
'core-templates' -> 'adminlte-templates'
https://github.com/InfyOmLabs/core-templates package is deprecated
> Replace default values. infyomlabs/core-templates is deprecated

- templates/scaffold/datatable.stub
@param PHPDoc should dynamically point to $MODEL_NAME$
> fix hardcoded PHPDoc comment

- src/Commands/Scaffold/ScaffoldGeneratorCommand.php
laravel-generator errors with "There isn not input fields to generate" if there are fewer than 4 fields in input table.
> Reduce number of required fields in scaffold generator.

- src/Common/GeneratorField.php
- src/Generators/ModelGenerator.php
- src/Generators/Scaffold/ViewGenerator.php
- src/Utils/TableFieldsGenerator.php
Allow making not null fields to be required in model and in field name (although field name stubs would have to be changed to use html)
> Require is not null

- src/Commands/VueJs/VueJsGeneratorCommand.php
- src/Generators/VueJs/ControllerGenerator.php
- src/Generators/VueJs/ViewGenerator.php
Objects properties can not be accessed as array object['name'] but as object->name.
> Fixed Problems in Vue.js Generators when using PHP7.

- src/Common/GeneratorField.php
- src/Generators/SwaggerGenerator.php
- src/Utils/TableFieldsGenerator.php
#380 
While creating scaffold using `--fromTable`, descriptions of swagger doc should be taken from database column comments, if it is there.
> #380 Take swagger description from comments of DB Column

- src/Common/BaseRepository.php
In Laravel 5.8 the `getForeignKey` and `getQualifiedForeignKey` methods of the `BelongsTo` relationship have been renamed to `getForeignKeyName` and `getQualifiedForeignKeyName` respectively.
> getQualifiedForeignKey -> getQualifiedForeignKeyName

- config/laravel_generator.php
Steps to Reproduce ( **Issue will reproduce only when PR changes are not applied** ) :
1. Create module direct from table by using `php artisan infyom:scaffold ModelName --fromTable --tableName=tablename`
2. Enter your data to field and submit
Error messages display that `id is required field`.
Solution : 
id should not be added into `Model:rules` as required field. 
Add `excluded_fields` into config => options and defined `id` to there, so it is ignored while generating rules for module.
> Column `id` should not be required into rules while creating module

- src/Commands/BaseCommand.php
- src/Common/CommandData.php
- src/Common/GeneratorConfig.php
- src/Generators/MigrationGenerator.php
- templates/migration.stub
Issues Fixed : 
while creating crud using generator builder, when we enter custom table name generator  will take table name from model name. 
Also option `migrate` is not working
> Create CRUD with custom table name using generator builder

- src/Commands/BaseCommand.php
- src/Common/GeneratorConfig.php
If you want to run migration by skipping confirmation message ( Y | N), just pass option `--forceMigrate` with any command of infyom generator
> Option `forceMigrate` added to run migration

- src/Common/GeneratorFieldRelation.php
- src/Generators/ModelGenerator.php
How to  reproduce : #709 
**NOTE: `1tm` relation text should be taken from table name instead of column names.**
while we have migration like following:
```
public function up()
{
Schema::create('people', function (Blueprint $table) {
$table->bigIncrements('id');
$table->string('name');
$table->timestamps();
});
Schema::create('phones', function (Blueprint $table) {
$table->bigIncrements('id');
$table->string('phone_no');
$table->unsignedBigInteger('people_id')->nullable();
$table->timestamps();
$table->foreign('people_id')->references('id')->on('people');
});
Schema::create('addresses', function (Blueprint $table) {
$table->bigIncrements('id');
$table->string('address');
$table->unsignedBigInteger('people_id')->nullable();
$table->foreign('people_id')->references('id')->on('people');
}); …
```
> Fixed duplicate creation of relations #709

- samples/fields_sample.json
- src/Commands/BaseCommand.php
- src/Common/GeneratorField.php
- src/Generators/Scaffold/ViewGenerator.php
- src/Utils/TableFieldsGenerator.php
- tests/Utils/GeneratorFieldsInputUtilTest.php
* exclude filed from show page support added by option.  issue found [here](https://github.com/InfyOmLabs/laravel-generator/issues/734)
* InView option added for generate by json file.
**Example**
by json file
```
{
"name": "checkbox",
"dbType": "integer",
"htmlType": "checkbox",
"validations": "required",
"searchable": true,
"fillable": true,
"primary": false,
"inForm": true,
"inIndex": true,
"inView": false" // this option added
},
```
by terminal 
` body text textarea iv`  // you can skip filed from view using `iv`
> feat: exclude filed from show page support added with option InView (#734)

- src/Common/GeneratorField.php
- src/Utils/TableFieldsGenerator.php
field's length read from db schema and write into json file 
read field is nulable or not from db schema and write into json file 
here is command...
`php artisan infyom:scaffold A --fromTable --tableName=a --plural=a --skip=migration,controllers,api_controller,scaffold_controller,scaffold_requests,routes,api_routes,scaffold_routes,views,tests,menu,dump-autoload,model,repository -n
**Example**
```
{
"name": "category",
"dbType": "string,30:nullable",  // here write from DB
"htmlType": "select,Technology,LifeStyle,Education,Games",
"searchable": true
}
```
for more info found [here](https://github.com/InfyOmLabs/laravel-generator/issues/715)
> feat: #715 read length and nullable from table and add in a json file

- src/Generators/Scaffold/ViewGenerator.php
https://github.com/InfyOmLabs/laravel-generator/issues/733
`min` and `max` rules now validate from html field too.
How  to test ?
change generator branch to  `vishal/733_validations` and adminlte-template branch to `vishal/733` then run `composer update`
Create any module with rules `min:5` OR `max:5` and check related HTML field
> #733 add min|max validations to html field

- src/Commands/BaseCommand.php
- src/Common/CommandData.php
- src/Common/GeneratorConfig.php
- src/Utils/TableFieldsGenerator.php
- templates/model/model.stub
#168 
- when user has more then one DB (connection 1 and connection2), if connection 1 is set into env and user want to create CRUD from connection2, so he does not need to change env just use option `--connection=connection2`
e.g `php artisan infyom:scaffold --fromTable --tableName=users --connection=connectionName`
> #168 Multi Database (connection) support added

- src/Generators/API/APIRoutesGenerator.php
- src/Generators/Scaffold/MenuGenerator.php
- src/Generators/Scaffold/RoutesGenerator.php
- while executing scaffold, api command twice for same model, menus and routes are duplicating.
- menus and routes are not generating twice for same model into `menu.blade.php`, `api.php` and `web.php`
> Don't repeat menus and routes

- templates/api/controller/api_controller.stub
- templates/api/controller/model_api_controller.stub
- templates/app_base_controller.stub
How to test:
Run `php artisan infyom:publish` and replace just `AppBaseController.php`, now create any API using command
- In current version when we delete record its return message like 
```
{
data : 1,
success: true,
message: Model deleted successfully.
}
```
by making this changing it should return :
```
{
success: true,
message: Model deleted successfully.
}
```
> Send only success message on record deletion

- src/Commands/Publish/PublishUserCommand.php
- src/InfyOmGeneratorServiceProvider.php
- templates/routes/user.stub
- templates/user/create_user_request.stub
- templates/user/update_user_request.stub
- templates/user/user_controller.stub
- templates/user/user_controller_without_repository.stub
- templates/user/user_repository.stub
- User CRUD publish with default field which are provided by Laravel framework.
-  Publish User CRUD via using `php artisan infyom.publish:user` command
**following files generated by this command**
1. Controller
2. Repository
3. Views
4. Route
5. Menu
6. Requests
before fire this command need to complete installation steps and publish layouts
after publish user CRUD. 
for more detail about issue.
How to integrate Users with scaffold? [#666](https://github.com/InfyOmLabs/laravel-generator/issues/666)
Add this package in. composer and update it. do all step of infyom pkg installations. 
```
"infyomlabs/laravel-generator": "dev-issue-666-user-publish",
"infyomlabs/adminlte-templates": "dev-issue-666-user-crud-template",
```
then after run command   `php artisan infyom.publish:user`
Check …
> Publish User Crud with default fields

- src/Generators/ModelGenerator.php
This should work around an edge case where the swagger documentation code is attempting to determine if a field is required before the validation rules have been generated for that particular field.
The symptom being that "$REQUIRED_FIELDS$" is always empty when generating a model - the data for this property is created at the generateSwagger method which sources from the generateRequiredFields method.
The generateRequiredFields method iterates through the fields and checks to see if any of the validations are required - the problem being that due to the ordering of calls in fillTemplate, the validations have not yet been determined and thus it will always fail.
> Fix rule validations being populated after they are already required by swagger model doc

- src/Common/GeneratorField.php
- src/Generators/ModelGenerator.php
- src/Utils/TableFieldsGenerator.php
Currently decimal fields are populated as floats inside generated model casts which is not ideal as the two are not equivalent.
This casts them to decimal (defaulting to two decimal places) and should automatically determine the correct number of decimal places if sourcing from a database.
Note that the laravel 'decimal' cast actually returns a string via number_format as there is no native PHP decimal type - usage of bcmath, a decimal or money class is probably the desired end state for most users however that is outside the scope of this project.
> Fix decimal fields being generated as floats inside model casts

- src/Generators/ModelGenerator.php
These are generated based on the column data as reported from the database.
For instance, assuming an example database structure as follows:
```sql
CREATE TABLE `country` (
`code` char(2) NOT NULL,
`name` varchar(255) NOT NULL,
`continent_name` varchar(255) DEFAULT NULL,
`upstream_id` int(11) DEFAULT NULL,
PRIMARY KEY (`code`)
)
```
With this commit in place we will now automatically generate model rules as follows:
```diff
public static $rules = [
-        'name' => 'required'
+        'name' => 'required|string|max:255',
+        'continent_name' => 'nullable|string|max:255',
+        'upstream_id' => 'nullable|integer'
];
```
Note that this only matches the most common column types - any others will simply generate no extra rules as per the original behaviour.
> Add basic attribute validation when generating from a database table

- src/Generators/ModelGenerator.php
- templates/api/test/api_test.stub
- templates/model/model.stub
- templates/test/repository_test.stub
In Laravel 8 models have to implement HasFactory trait, and factory(Model::class) is replaced by Model::factory()
> Fixed factories for Laravel 8

- src/Generators/Scaffold/ViewGenerator.php
Replacing `$FIELD_NAME$` before `fill_template_with_field_data_locale()` otherwise also
`$FIELD_NAME$` get replaced with `@lang('models/$modelName.fields.$value')`
and so we don't have `$FIELD_NAME$` in `table_header_locale.stub`.
@see issue https://github.com/InfyOmLabs/laravel-generator/issues/887
We could need 'raw' field name in header for example for sorting.
We still have $FIELD_NAME_TITLE$ replaced with @lang('models/$modelName.fields.$value')
> Suggested solution for issue #887
