src/Commands/BaseCommand.php
Support composer dump-autoload
see #7
=> Support composer dump-autoload

src/Generators/ModelGenerator.php
In the previous pull request I left to separate fields with commas and that was causing an error.
=> Fix separating fields with commas

samples/fields_sample.json, src/Generators/API/APIControllerGenerator.php, src/Generators/Scaffold/ViewGenerator.php
Now you can use both checkbox and checkbox-group
=> adjusted your checkbox 

src/Utils/TableFieldsGenerator.php, templates/scaffold/routes/routes.stub
This pull request is part of another pull request in `core-templates` repo. Check [https://github.com/InfyOmLabs/core-templates/pull/3](https://github.com/InfyOmLabs/core-templates/pull/3) for more information.
=> Remove GET delete route since it's not needed to directly destroy a record

config/laravel_generator.php
=> added deleted_at

samples/fields_sample.json
=> added boolean

src/Commands/BaseCommand.php, src/Common/GeneratorConfig.php
Added option to suppress auto-loader generation. default is true (generate autoloader)
=> Added option to suppress auto-loader generation.

templates/scaffold/controller/datatable_controller.stub
added $ROUTES_AS_PREFIX$ to the datatable return route
=> Fixed bad route for datatable

src/Generators/Scaffold/ViewGenerator.php
2 New fields added 
```
{
"fieldInput": "is_active:boolean", /* BOOLEAN CHECKBOX */
"htmlType": "bool-checkbox:checked",
"validations": "",
"searchable": true,
"fillable": true,
"primary": false,
"inForm": true,
"inIndex": false
},
```
```
{
"fieldInput": "is_published:boolean",   /* BOOTSTRAP STYLED TOGGLE SWICH */
"htmlType": "toggle-switch",
"validations": "",
"searchable": true,
"fillable": true,
"primary": false,
"inForm": true,
"inIndex": false
}
```
both with options..
OPTIONS FOR TOGGLE SWITCH 
{!! Form::checkbox('$FIELD_NAME$', 1, true,  ['data-toggle' => 'toggle', 'data-size' => 'small', 'data-onstyle'=>'success', 'data-offstyle' => 'danger', 'data-on' => '<i class="fa fa-check"></i> ON' , 'data-off' => '<i class="fa fa-times"></i> Off']); !!}
ADD TO DOCS
Bootstrap Toggle …
=> Added fields

samples/fields_sample.json
ADDED:
BOOLEAN CHECKBOX - w/Options
BOOTSTRAP TOGGLE SWITCH - w/Options
=> ADDED NEW FIELDS

src/Common/GeneratorConfig.php
$VIEW_PREFIX${GENERATED CRUD} 
IS NOW 
$VIEW_PREFIX$/{GENERATED CRUD}
=> update to seperate directories

config/laravel_generator.php
'route' =>   $ROUTE_PREFIX$  ex: admin.? uses
'view' =>   $VIEW_PREFIX$  in: backend  :example views directory
=> added instructions for using the new prefixes

templates/scaffold/controller/datatable_controller.stub
=> Updated to use prefixes

templates/scaffold/controller/controller.stub
now working with new 
$ROUTE_PREFIX$  ex: admin
$VIEW_PREFIX$  ex: backend
=> Updated to use the new prefixes

src/Commands/BaseCommand.php
made it make a bit more sense.
=> fixed instruction

templates/scaffold/controller/controller.stub, templates/scaffold/controller/datatable_controller.stub
fixed route named prefix errors in 
controller.stub
datatable_controller.stub
=> fixed route named prefix in controllers

templates/migration.stub
=> fix generated migration name

src/Utils/TableFieldsGenerator.php
#239
please don't mind me closing PRs  .. I am new to git
=> fixed generate unsigned schema fields

src/Common/GeneratorConfig.php, src/Generators/Scaffold/ControllerGenerator.php
Remove datatables file in DataTable folder when using rollback command.
Add $MODEL_NAME_SLASH$ useful for routes generation
=> Add rollback include datatable file, Add $MODEL_NAME_SLASH$ to GeneratorConfig

templates/api/controller/api_controller.stub
Fix to false return of API controllers.
=> Fix to false return of API controllers.

src/Utils/TableFieldsGenerator.php
Bug fix so textareas from htmlType text can be generated.
=> Fix: Remove backtick from textarea so it will generate fields.

src/Commands/BaseCommand.php
Fixed implode call syntax on line 188
=> JSON model file generation fix

src/Utils/TableFieldsGenerator.php
see https://github.com/InfyOmLabs/laravel-generator/pull/364
=> bug fix when using fromTable option

src/Commands/BaseCommand.php, src/Common/CommandData.php
Generate fields when using InfyOmLabs/generator-builder
Allow Auto Migrate
=> Solve generating fields from jsonFromGUI

samples/fields_sample.json
this way people now the function already exists
=> added default to foreign key output example

src/Commands/Publish/PublishTemplateCommand.php
=> #595 publish swagger templates

config/laravel_generator.php, src/Commands/BaseCommand.php, src/Common/CommandData.php, src/Common/GeneratorConfig.php, src/Utils/TableFieldsGenerator.php
=> Ignore fields while generating from table + doctrine mappings support

src/helpers.php
#520 removed duplicate function
=> #520 removed duplicate function

src/Commands/RollbackGeneratorCommand.php
#514 Rollback command docs refactored
=> #514 Rollback command docs refactored

src/Utils/HTMLFieldGenerator.php
#439 removed duplicate code of HTML field generator
=> #439 removed duplicate code of HTML field generator

src/Generators/TestTraitGenerator.php
=> #498 take value as date-time for db type timestamp into TestTrait

src/Commands/BaseCommand.php, src/Commands/RollbackGeneratorCommand.php, src/Common/GeneratorConfig.php
#479 support custom plural model name
=> #479 support custom plural model name

samples/fields_sample.json
#384 minor change in sample json file
=> #384 minor change in sample json file

src/Generators/Scaffold/ControllerGenerator.php
#521 fix non-searchable fields on datatable
=> #521 Fix Non-searchable fields on Datatable

src/Common/GeneratorFieldRelation.php, src/Generators/ModelGenerator.php, src/Utils/TableFieldsGenerator.php
#475 Fix relationship method names as per foreign key
also fixed Issue :#493
=> #475 Fix relationship method names as per foreign key

templates/api/test/api_test.stub, templates/test/api_test_trait.stub, templates/test/repository_test.stub
Solves #516, while updating the API tests to use TestResponse object for assertions
=> Update to 5.5 test syntax

config/laravel_generator.php, src/Commands/Publish/GeneratorPublishCommand.php, src/Common/GeneratorConfig.php, src/Generators/RepositoryTestGenerator.php, templates/api/test/api_test.stub, templates/test/api_test_trait.stub, templates/test/repository_test.stub, templates/test/trait.stub, templates/vuejs/test/api_test.stub
#516 
Support for tests namespaces 
Support dynamic API route of API test cases
Refactored Name of Test cases
=> #516 Support for tests namespaces

src/Commands/Publish/GeneratorPublishCommand.php, templates/test/api_test_trait.stub, templates/test/trait.stub
InfyOmLabs/adminlte-generator#18
Skip timestamps fields while asserting model data
=> #18 skip timestamps fields while asserting model data

src/Generators/Scaffold/ViewGenerator.php, src/Generators/VueJs/ViewGenerator.php
#545 fix issue of paginate while using datatables
=> #545 fix issue of paginate while using datatables

templates/scaffold/datatable.stub
* save current state for datatable record
=> save current state for datatable record

src/Generators/ModelGenerator.php, src/Generators/SwaggerGenerator.php
#551 minor swagger fix of date-time fields
=> #551 minor swagger fix of date-time fields

src/Utils/HTMLFieldGenerator.php
Issue : https://github.com/InfyOmLabs/generator-builder/issues/13
=> #generator-builder/13 toggle switch field support

src/Commands/BaseCommand.php, src/Common/CommandData.php, src/Common/GeneratorConfig.php
https://github.com/InfyOmLabs/generator-builder/issues/18
=> #18 Override options in config from GUI input

src/Common/GeneratorConfig.php
Issue: https://github.com/InfyOmLabs/generator-builder/issues/18 fix prefix option from GUI input
=> #18 Fix prefix option from GUI input

src/Common/GeneratorFieldRelation.php, src/Generators/ModelGenerator.php
Fix hasOne relationship method name
=> Fix hasOne relationship method name

src/Common/BaseRepository.php
=> #665 Do not call model events twice while create/update modal

samples/fields_sample.json, src/Common/GeneratorFieldRelation.php
=> #664 Custom relationship name support added

CONTRIBUTING.md
=> #673 Contributing file with some basic details

src/Commands/BaseCommand.php
=> #672 Run migration when migration path is changed

config/laravel_generator.php, src/Commands/BaseCommand.php, src/Common/GeneratorConfig.php, src/Generators/FactoryGenerator.php, templates/factories/model_factory.stub
you need to define factory path into `laravel_generator` config
while running any command `api. scaffold and api_scaffold` you just need to pass option `factory` 
e.g `php artisan infyom:scaffolf MyModel --factory`
=> Generate model factory with its fields by just adding option --factory

config/laravel_generator.php, src/Commands/BaseCommand.php, src/Commands/Publish/LayoutPublishCommand.php, src/Commands/Publish/PublishTemplateCommand.php, src/Common/GeneratorConfig.php, src/Generators/MigrationGenerator.php, src/Generators/Scaffold/MenuGenerator.php, src/helpers.php
* Use database_path & resource_path helper instant of base_path
=> Use database_path & resource_path helpers

config/laravel_generator.php, src/Commands/BaseCommand.php, src/Common/GeneratorConfig.php, src/Generators/SeederGenerator.php, templates/seeds/model_seeder.stub
you need to define seeder path into `laravel_generator` config
while running any command `api. scaffold and api_scaffold` you just need to pass option `seeder` 
e.g `php artisan infyom:scaffold MyModel --seeder`
=> Generate seeder by just adding option --seeder

src/Common/GeneratorFieldRelation.php, src/Generators/ModelGenerator.php, src/Utils/TableFieldsGenerator.php
#706 fix 1tm relationship method name as per its foreign key
=> #706 fix 1tm relationship method name as per its foreign key

.travis.yml, composer.json
[Laravel 6 ](https://laravel.com/docs/6.0) support added
=> Laravel 6 support added

src/Utils/TableFieldsGenerator.php
#724, #722  fix mtm relationship
=> #724 fix mtm relationship

src/Generators/ModelGenerator.php
=> Primary key should not be added as required field into rules #721

src/Common/CommandData.php, src/Generators/ModelGenerator.php
* #729 timestamps disabled from config
=> #729 timestamps disabled from config

src/Common/GeneratorConfig.php, src/Generators/Scaffold/ViewGenerator.php
=> Add `files => true` when file input is given

src/Commands/RollbackGeneratorCommand.php, src/Generators/Scaffold/ViewGenerator.php
https://github.com/InfyOmLabs/laravel-generator/issues/116
What's new added: 
you can now rollback specific views by running
`php artisan infyom:rollback Model scaffold --views=edit,create`
=> Rollback specific view

src/Generators/ModelGenerator.php, src/Generators/Scaffold/RequestGenerator.php, templates/api/request/update_request.stub, templates/scaffold/request/update_request.stub
=> #735 unique rules implemented while updating record

src/Generators/API/APIRequestGenerator.php
Issue : #735 fix unique rules in updateAPIRequest
For Test: 
Create scaffold with api by `api_scaffold` command & Check  `UpdateAPIRequest`
=> #735 Fix unique rules for API

src/Generators/ModelGenerator.php
#766 Fix namespace of import for Str class
=> 5.7 Issue #766 

src/Common/GeneratorConfig.php
#708 prefix separated by slash instead of a comma
=> #708 prefix separated by slash instead of a comma

src/Utils/HTMLFieldGenerator.php
#809 fix to generate toggle switch field
=> #809 fix to generate toggle switch field

src/Generators/ModelGenerator.php
Based on https://docs.phpdoc.org/latest/references/phpdoc/tags/var.html
=> PHPDoc should have a dolar before the property name

src/Commands/Publish/PublishTemplateCommand.php, src/helpers.php
=> Support for templates from other vendors

src/Generators/Scaffold/ViewGenerator.php
Added check if localized template for selectTable. Now load always not localized select.
=> Missing locale for selectTable
